### PR TITLE
feat(rpb): add radicle planning board iframe

### PR DESCRIPTION
**Pull request by QZera**

### CODE REVIEW

**Comment by QZera** [comment]
Related `radicle-planning-boards` PR: https://github.com/cytechmobile/radicle-planning-boards/pull/25

**Review by maninak — DISMISSED** [review]
Well done! :clap:

**Comment by maninak** [comment]
Hmm, I'm not sure to which URL I have to go to see this working, but from the looks of it I have to also be running `radicle-planning-boards` locally to see the iframe.

Could we instead take the build artifact of that repo and commit it in this one? This way the deployed app will work fully.

I guess that process could be automated later after the prototype phase as vite plugin or monorepo or something.

**Comment by maninak** [comment]
If my OS is set in dark mode and the host app is set in light mode does the iframed app have a flash of black background before the vue app is initialized and able to handle the URL param `initialTheme`?

If that's the case, we should consider if setting a specific style overloading the the [body bg color](https://github.com/cytechmobile/radicle-planning-boards/blob/22b9344eee23da1057920cd398220f53566efd47/assets/css/tailwind.css#L118) would solve it.

**Comment by QZera** [comment]
> If my OS is set in dark mode and the host app is set in light mode does the iframed app have a flash of black background before the vue app is initialized and able to handle the URL param `initialTheme`?
> 
> If that's the case, we should consider if setting a specific style overloading the the [body bg color](https://github.com/cytechmobile/radicle-planning-boards/blob/22b9344eee23da1057920cd398220f53566efd47/assets/css/tailwind.css#L118) would solve it.

I had this issue, and weirdly enough, changing the body background didn't have any effect.
I resolved it by hiding the iframe while it's loading ([Source](https://css-tricks.com/snippets/html/get-rid-of-white-flash-when-iframe-loads/))

**Comment by QZera** [comment]
> Hmm, I'm not sure to which URL I have to go to see this working, but from the looks of it I have to also be running `radicle-planning-boards` locally to see the iframe.
> 
> Could we instead take the build artifact of that repo and commit it in this one? This way the deployed app will work fully.
> 
> I guess that process could be automated later after the prototype phase as vite plugin or monorepo or something.

I've hardcoded `localhost:3000` for the iframe `src`. I think we could simply change it to the deployed `rpb` url and it should work. (That way we always have the latest version of `rpb` as well)

Thoughts?

**Comment by maninak** [comment]
> I've hardcoded `localhost:3000` for the iframe `src`. I think we could simply change it to the deployed `rpb` url and it should work.

Sure, we can do that too. But please check [this discussion](https://github.com/cytechmobile/radicle-planning-boards/pull/25#discussion_r1421817917) for context first.

**Review by maninak — APPROVED** [review]

**Pull request merged**
